# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/ for more information

run:
  timeout: 5m
  tests: true
  skip-dirs:
    - vendor
  skip-files:
    - ".*\\.pb\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/example/k8s-view
  govet:
    check-shadowing: true
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
        - gocritic
        - lll
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
        - gocritic
        - lll
  max-issues-per-linter: 50
  max-same-issues: 10
  exclude:
    - "Error return value of `w\\.Write` is not checked"
    - "Error return value of `filepath\\.Abs` is not checked"
    - "Error return value of `fmt\\.Sscanf` is not checked"
    - "Error return value of `json\\.Marshal` is not checked"
    - "Error return value of `unstructured\\.Nested.*` is not checked"
    - "Error return value of `schema\\.ParseGroupVersion` is not checked"
    - "Error return value of `net\\.SplitHostPort` is not checked"
    - "Error return value of `seeker\\.Seek` is not checked"
    - "Error return value of `io\\.ReadAll` is not checked"
    - "Error return value of `x509\\.SystemCertPool` is not checked"
    - "Error return value of `s\\.repo\\.Query.*` is not checked"
    - "Error return value of `stdinWriter\\.Write` is not checked"
    - "Error return value of `conn\\.WriteMessage` is not checked"
    - "Error return value of `metricsv\\.NewForConfig` is not checked"
