# golangci-lint configuration file
# See https://golangci-lint.run/usage/configuration/ for more information

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly
  allow-parallel-runners: true
  issues:
    exclude-dirs:
      - vendor
    exclude-files:
      - ".*\\.pb\\.go$"

linters-settings:
  errcheck:
    check-type-assertions: true
    check-blank: true
  goconst:
    min-len: 3
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/example/k8s-view
  govet:
    enable-all: false
    disable:
      - fieldalignment
  lll:
    line-length: 120
  maligned:
    suggest-new: true
  misspell:
    locale: US
  nolintlint:
    allow-leading-space: true
    allow-unused: false
    require-explanation: false
    require-specific: false

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - gocritic
    - gocyclo
    - gofmt
    - goimports
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - noctx
    - nolintlint
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - errcheck
        - goconst
        - gocyclo
        - gocritic
        - lll
        - unused
        - shadow
        - gosimple
        - govet
        - ineffassign
        - staticcheck
  max-issues-per-linter: 200
  max-same-issues: 50
  exclude:
    - "Error return value.*is not checked"
    - "string `.*` has .* occurrences, make it a constant"
    - "cyclomatic complexity .* of func.*is high"
    - "hugeParam:.*is heavy"
    - "rangeValCopy:.*consider pointers"
    - "appendCombine:.*can combine"
    - "ifElseChain:.*rewrite if-else"
    - "typeAssertChain:.*rewrite if-else"
    - "sprintfQuotedString:.*use %q"
    - "unnamedResult:.*consider giving a name"
    - "elseif:.*can replace"
    - "emptyStringTest:.*replace"
    - "octalLiteral:.*use new octal"
    - "httpNoBody:.*should be preferred"
    - "paramTypeCombine:.*could be replaced"
    - "evalOrder:.*may want to evaluate"
    - "unnecessary conversion"
    - "G115:.*integer overflow"
    - "G402:.*TLS InsecureSkipVerify"
    - "G114:.*Use of net/http serve"
    - "SA2001:.*empty critical section"
    - "S1031:.*unnecessary nil check"
    - "shadow:.*declaration of.*shadows"
    - "ineffectual assignment"
    - "The line is .* characters long"
    - "func `contains` is unused"
