// @title DKonsole API
// @version 1.2.1
// @description API para gestión de recursos Kubernetes y Helm releases
// @termsOfService http://swagger.io/terms/

// @contact.name DKonsole Support
// @contact.url https://github.com/example/k8s-view

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:8080
// @BasePath /
// @schemes http https

// @securityDefinitions.apikey Bearer
// @in header
// @name Authorization
// @description JWT token obtenido del endpoint /api/login. Formato: "Bearer {token}"

package main

import (
	"flag"
	"mime"
	"net/http"
	"net/url"
	"os"
	"path/filepath"
	"strings"

	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/clientcmd"
	"k8s.io/client-go/util/homedir"
	metricsv "k8s.io/metrics/pkg/client/clientset/versioned"

	httpSwagger "github.com/swaggo/http-swagger"

	"github.com/example/k8s-view/internal/api"
	"github.com/example/k8s-view/internal/auth"
	"github.com/example/k8s-view/internal/cluster"
	"github.com/example/k8s-view/internal/health"
	"github.com/example/k8s-view/internal/helm"
	"github.com/example/k8s-view/internal/k8s"
	"github.com/example/k8s-view/internal/logo"
	"github.com/example/k8s-view/internal/middleware"
	"github.com/example/k8s-view/internal/models"
	"github.com/example/k8s-view/internal/pod"
	"github.com/example/k8s-view/internal/prometheus"
	"github.com/example/k8s-view/internal/utils"

	_ "github.com/example/k8s-view/docs" // docs is generated by Swag CLI
)

// ResponseWriter wrapper to fix Content-Type after FileServer sets it
type contentTypeFixer struct {
	http.ResponseWriter
	path string
}

func (c *contentTypeFixer) WriteHeader(code int) {
	// Fix Content-Type based on file extension before writing headers
	ext := filepath.Ext(c.path)
	switch ext {
	case ".js":
		c.ResponseWriter.Header().Set("Content-Type", "application/javascript; charset=utf-8")
	case ".css":
		c.ResponseWriter.Header().Set("Content-Type", "text/css; charset=utf-8")
	case ".json":
		c.ResponseWriter.Header().Set("Content-Type", "application/json; charset=utf-8")
	case ".png":
		c.ResponseWriter.Header().Set("Content-Type", "image/png")
	case ".jpg", ".jpeg":
		c.ResponseWriter.Header().Set("Content-Type", "image/jpeg")
	case ".svg":
		c.ResponseWriter.Header().Set("Content-Type", "image/svg+xml")
	case ".woff", ".woff2":
		c.ResponseWriter.Header().Set("Content-Type", "font/woff2")
	case ".ttf":
		c.ResponseWriter.Header().Set("Content-Type", "font/ttf")
	case ".eot":
		c.ResponseWriter.Header().Set("Content-Type", "application/vnd.ms-fontobject")
	default:
		// Try to detect MIME type from extension
		if ct := mime.TypeByExtension(ext); ct != "" {
			c.ResponseWriter.Header().Set("Content-Type", ct)
		}
	}
	c.ResponseWriter.WriteHeader(code)
}

func main() {
	var kubeconfig *string
	if home := homedir.HomeDir(); home != "" {
		kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
	} else {
		kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
	}
	flag.Parse()

	// use the current context in kubeconfig
	config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		utils.LogWarn("Error building kubeconfig from flags, falling back to in-cluster config", map[string]interface{}{
			"error": err.Error(),
		})
		config, err = rest.InClusterConfig()
		if err != nil {
			utils.LogError(err, "Failed to get in-cluster config", nil)
			panic(err.Error())
		}
	}

	// create the clientset
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}

	metricsClient, _ := metricsv.NewForConfig(config)

	dynamicClient, err := dynamic.NewForConfig(config)
	if err != nil {
		panic(err.Error())
	}

	handlersModel := &models.Handlers{
		Clients:       make(map[string]*kubernetes.Clientset),
		Dynamics:      make(map[string]dynamic.Interface),
		Metrics:       make(map[string]*metricsv.Clientset),
		RESTConfigs:   make(map[string]*rest.Config),
		PrometheusURL: os.Getenv("PROMETHEUS_URL"),
	}
	handlersModel.Clients["default"] = clientset
	handlersModel.Dynamics["default"] = dynamicClient
	handlersModel.RESTConfigs["default"] = config
	if metricsClient != nil {
		handlersModel.Metrics["default"] = metricsClient
	}

	// Initialize services
	authService := auth.NewService(handlersModel)
	clusterService := cluster.NewService(handlersModel)
	k8sService := k8s.NewService(handlersModel, clusterService)
	apiService := api.NewService(handlersModel, clusterService)
	helmService := helm.NewService(handlersModel, clusterService)
	podService := pod.NewService(handlersModel, clusterService)
	prometheusService := prometheus.NewHTTPHandler(handlersModel.PrometheusURL, clusterService)
	logoService := logo.NewService("./data")

	mux := http.NewServeMux()
	// Helper for authenticated routes
	// SecurityHeadersMiddleware is applied first to ensure all responses have security headers
	secure := func(h http.HandlerFunc) http.HandlerFunc {
		return middleware.SecurityHeadersMiddleware(enableCors(RateLimitMiddleware(CSRFMiddleware(AuditMiddleware(authService.AuthMiddleware(h))))))
	}

	// Helper for authenticated Handler (for Swagger which returns http.Handler)
	secureHandler := func(h http.Handler) http.Handler {
		// Convert Handler to HandlerFunc and apply authentication middleware
		handlerFunc := func(w http.ResponseWriter, r *http.Request) {
			h.ServeHTTP(w, r)
		}
		// Apply the same security chain as secure() but wrap the Handler
		return middleware.SecurityHeadersHandler(http.HandlerFunc(
			enableCors(RateLimitMiddleware(CSRFMiddleware(AuditMiddleware(authService.AuthMiddleware(handlerFunc)))))),
		)
	}

	// Helper for public routes
	public := func(h http.HandlerFunc) http.HandlerFunc {
		return middleware.SecurityHeadersMiddleware(enableCors(RateLimitMiddleware(AuditMiddleware(h))))
	}

	mux.HandleFunc("/api/login", middleware.SecurityHeadersMiddleware(enableCors(LoginRateLimitMiddleware(AuditMiddleware(authService.LoginHandler)))))
	mux.HandleFunc("/api/logout", public(authService.LogoutHandler))
	mux.HandleFunc("/api/me", secure(authService.MeHandler))
	// Health check endpoint (also available as /health for compatibility)
	mux.HandleFunc("/healthz", middleware.SecurityHeadersMiddleware(health.HealthHandler))
	mux.HandleFunc("/health", middleware.SecurityHeadersMiddleware(health.HealthHandler))

	// Swagger documentation - protected with authentication
	mux.Handle("/swagger/", secureHandler(httpSwagger.WrapHandler))

	// K8s handlers - using services
	mux.HandleFunc("/api/namespaces", secure(k8sService.GetNamespaces))
	mux.HandleFunc("/api/resources", secure(k8sService.GetResources))
	mux.HandleFunc("/api/resources/watch", secure(k8sService.WatchResources))
	mux.HandleFunc("/api/resource/yaml", secure(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			k8sService.GetResourceYAML(w, r)
		} else if r.Method == http.MethodPut {
			k8sService.UpdateResourceYAML(w, r)
		} else {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))
	mux.HandleFunc("/api/resource/import", secure(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			k8sService.ImportResourceYAML(w, r)
		} else {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))

	// API handlers - using services
	mux.HandleFunc("/api/apis", secure(apiService.ListAPIResources))
	mux.HandleFunc("/api/apis/resources", secure(apiService.ListAPIResourceObjects))
	mux.HandleFunc("/api/apis/yaml", secure(apiService.GetAPIResourceYAML))
	mux.HandleFunc("/api/crds", secure(apiService.GetCRDs))
	mux.HandleFunc("/api/crds/resources", secure(apiService.GetCRDResources))
	mux.HandleFunc("/api/crds/yaml", secure(apiService.GetCRDYaml))

	mux.HandleFunc("/api/scale", secure(k8sService.ScaleResource))
	mux.HandleFunc("/api/overview", secure(k8sService.GetClusterStats))

	// Helm handlers - using services
	mux.HandleFunc("/api/helm/releases", secure(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			helmService.GetHelmReleases(w, r)
		} else if r.Method == http.MethodDelete {
			helmService.DeleteHelmRelease(w, r)
		} else if r.Method == http.MethodPost {
			helmService.UpgradeHelmRelease(w, r)
		} else {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))
	mux.HandleFunc("/api/helm/releases/install", secure(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodPost {
			helmService.InstallHelmRelease(w, r)
		} else {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))

	// Pod handlers - using services
	// WebSocket endpoints need connection limiting
	mux.HandleFunc("/api/pods/logs", secure(middleware.WebSocketLimitMiddleware(podService.StreamPodLogs)))
	mux.HandleFunc("/api/pods/events", secure(podService.GetPodEvents))
	mux.HandleFunc("/api/pods/exec", secure(middleware.WebSocketLimitMiddleware(podService.ExecIntoPod)))

	mux.HandleFunc("/api/resource", secure(k8sService.DeleteResource))
	mux.HandleFunc("/api/cronjobs/trigger", secure(k8sService.TriggerCronJob))
	// Logo handlers - using service
	mux.HandleFunc("/api/logo", secure(func(w http.ResponseWriter, r *http.Request) {
		if r.Method == http.MethodGet {
			logoService.GetLogo(w, r)
		} else if r.Method == http.MethodPost {
			logoService.UploadLogo(w, r)
		} else {
			http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		}
	}))
	// Prometheus handlers - using services
	mux.HandleFunc("/api/prometheus/status", secure(prometheusService.GetStatus))
	mux.HandleFunc("/api/prometheus/metrics", secure(prometheusService.GetMetrics))
	mux.HandleFunc("/api/prometheus/pod-metrics", secure(prometheusService.GetPodMetrics))
	mux.HandleFunc("/api/prometheus/cluster-overview", secure(prometheusService.GetClusterOverview))

	// Serve static files from frontend build
	staticDir := "./static"
	if _, err := os.Stat(staticDir); os.IsNotExist(err) {
		utils.LogWarn("Static directory not found, frontend will not be served", map[string]interface{}{
			"static_dir": staticDir,
		})
	} else {
		// Middleware to fix Content-Type for static files and add security headers
		secureStaticFiles := func(next http.Handler) http.Handler {
			return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
				// Wrap ResponseWriter to fix Content-Type
				fixer := &contentTypeFixer{
					ResponseWriter: w,
					path:           r.URL.Path,
				}

				// Apply security headers
				middleware.SecurityHeadersHandler(next).ServeHTTP(fixer, r)
			})
		}

		assetsDir := filepath.Join(staticDir, "assets")
		fileServer := http.FileServer(http.Dir(assetsDir))
		mux.Handle("/assets/", secureStaticFiles(http.StripPrefix("/assets/", fileServer)))

		mux.HandleFunc("/favicon.ico", middleware.SecurityHeadersMiddleware(func(w http.ResponseWriter, r *http.Request) {
			http.ServeFile(w, r, filepath.Join(staticDir, "favicon.ico"))
		}))
		mux.HandleFunc("/robots.txt", middleware.SecurityHeadersMiddleware(func(w http.ResponseWriter, r *http.Request) {
			http.ServeFile(w, r, filepath.Join(staticDir, "robots.txt"))
		}))

		mux.HandleFunc("/", middleware.SecurityHeadersMiddleware(func(w http.ResponseWriter, r *http.Request) {
			if strings.HasPrefix(r.URL.Path, "/api") {
				http.NotFound(w, r)
				return
			}
			if strings.HasPrefix(r.URL.Path, "/assets/") {
				http.NotFound(w, r)
				return
			}
			indexPath := filepath.Join(staticDir, "index.html")
			if _, err := os.Stat(indexPath); err == nil {
				http.ServeFile(w, r, indexPath)
			} else {
				http.NotFound(w, r)
			}
		}))
	}

	port := ":8080"
	utils.LogInfo("Server starting", map[string]interface{}{
		"port": port,
	})
	if err := http.ListenAndServe(port, mux); err != nil {
		utils.LogError(err, "Server failed", nil)
		panic(err)
	}
}

func enableCors(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		origin := r.Header.Get("Origin")
		allowedOrigins := os.Getenv("ALLOWED_ORIGINS")

		if origin == "" && r.Method != "OPTIONS" {
			next(w, r)
			return
		}

		allowed := false
		if allowedOrigins != "" {
			origins := strings.Split(allowedOrigins, ",")
			for _, o := range origins {
				o = strings.TrimSpace(o)
				if o == origin {
					allowed = true
					break
				}
			}
		} else {
			if origin != "" {
				originURL, err := url.Parse(origin)
				if err == nil {
					host := r.Host
					if strings.Contains(host, ":") {
						host = strings.Split(host, ":")[0]
					}
					originHost := originURL.Host
					if strings.Contains(originHost, ":") {
						originHost = strings.Split(originHost, ":")[0]
					}
					if (originHost == "localhost" || originHost == "127.0.0.1" || originHost == host) &&
						(originURL.Scheme == "http" || originURL.Scheme == "https") {
						allowed = true
					}
				}
			}
		}

		if !allowed && origin != "" {
			http.Error(w, "Origin not allowed", http.StatusForbidden)
			return
		}

		if origin != "" {
			w.Header().Set("Access-Control-Allow-Origin", origin)
		}
		w.Header().Set("Access-Control-Allow-Methods", "GET, POST, PUT, DELETE, OPTIONS")
		w.Header().Set("Access-Control-Allow-Headers", "Content-Type, Authorization")
		w.Header().Set("Access-Control-Allow-Credentials", "true")
		w.Header().Set("Access-Control-Max-Age", "3600")

		if r.Method == "OPTIONS" {
			w.WriteHeader(http.StatusOK)
			return
		}

		next(w, r)
	}
}
