// Package docs is a placeholder for Swagger-generated documentation.
// This package is generated by running: swag init -g main.go
//
// When Swagger documentation is generated, this file will be replaced
// with the actual generated documentation.
package docs
